### ISSUE TITLE
Autobloom Not Working

### ISSUE THREAD

**Issue by TripSea6023** [willnode/autobloom#26]
I've followed the instructions and installed it, without changing or deleting the folder, enabling and disabling the "run on AC power" option, install with Administrator Privileges, and yet it doesn't seem to work.

**Comment by eltrevii** [comment]
so it doesnt work after you reboot?

**Comment by andreiaky** [comment]
Same here. It seems that the mpv folder is empty and the readme file is not giving much information about how to install it. For example, after I install mpv I have the .com and .exe files, but I can't find the .dll files anywhere. Maybe it should be documented a little better? Thanks.

**Comment by eltrevii** [comment]
oh sorry i forgot to include it with the release im really sorry

**Comment by andreiaky** [comment]
There is no problem. 😆  The .gitignore file should be modified I guess. And the inclusion of that files.

**Comment by eltrevii** [comment]
no, actually we cannot upload the files to github because mpv is 100mb so i will make autobloom auto-download mpv or something

**Comment by eltrevii** [comment]
@TripSea6023 @andreiaky it works now, check out the [latest release](https://github.com/willnode/autobloom/releases)

**Comment by eltrevii** [comment]
@willnode from now on if we release new versions, we will use actions to build releases from now on, because it auto-downloads mpv and bundles it with autobloom

**Comment by eltrevii** [comment]
did the issue get fixed?

**Comment by eltrevii** [comment]
is it fixed now? @TripSea6023 @andreiaky

**Comment by andreiaky** [comment]
Not at my pc for a while. I will let you know next week for sure.

**Comment by andreiaky** [comment]
Ok I will start testing now. I will let you know if it works

**Comment by andreiaky** [comment]
It is still not working. And after uninstalling it seems there is something hooking the file and it won't let me delete the folder because a script is still running there. I tried testing with the latest release and the mpv is there and that's ok. I don't know what could cause the problem. Maybe the system is loading other items that have higher priority than this script? Here I made a video. I tested it on a newly installed vm with Windows 11 Pro. Try testing it on a virtual machine before releasing it. 

https://github.com/willnode/autobloom/assets/80176224/b08dfd97-9241-43f8-bd1a-fd6a48752100

**Comment by eltrevii** [comment]
hm thats weird, ill take a look at it later

**Comment by andreiaky** [comment]
Take your time

**Comment by yousefheroo028** [comment]
It's still not working.

**Comment by eltrevii** [comment]
hey, sorry for being absent for so long, im kinda busy lately but i will try to look into this later on, i think im halfway there in terms of troubleshooting, but i cant fix it right now, sorry

**Comment by eltrevii** [comment]
@TripSea6023 @andreiaky @yousefheroo028 i think i finally fixed it, it works on my machine and inside a virtual machine as well, i would appreciate if you guys test it, im sorry for not checking on this for so long, but i will try to be more active now

link to download: https://github.com/willnode/autobloom/releases/download/v2.5/autobloom-v2.5.zip
(or just go to releases)
